Fix to use dynamixel servo motors as neck joints of SOAR
sbgisen/dynamixel_control_hw pull request #5
Opened 2024-11-26 03:27 UTC by ChiroruNeko

## Summary
SOARの首パン軸、チルト軸でDynamixelを使用するための変更。

- fix #4 
- related to https://github.com/sbgisen/soar/issues/537

## Detail
- fix #4
- `urdf_param_name`ros paramの初期値を`/robot_description`に変更
- `gear_ratio`をros paramに追加
- `urdf`中の`rising`を参照してオフセットするよう修正

## Impact

## Test

* [x] ビルドが通った
* [x] 実機環境で動作した

## Attention

2024-11-26 04:30 UTC, jsupratman13 reviewed
Offsetについてだけど、確か dynamixel側で homing offsetを設定すると0~2piから-pi~piに変更できると思う。hardware interface 側はどう扱っているの？

https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#modifying-control-values

2024-11-26 04:30 UTC, jsupratman13 commented on include/dynamixel_control_hw/hardware_interface.hpp
> +        std::string urdf_param_name("/robot_description");
この変更点は必要無い
urdf_param_name パラメータで変更できるので

2024-11-26 04:41 UTC, jsupratman13 commented
後 ベースブランチは XMではなかったっけ？

2024-11-26 06:02 UTC, ChiroruNeko commented
> Offsetについてだけど、確か dynamixel側で homing offsetを設定すると0〜2piから-pi〜piに変更できると思う。hardware interface 側はどう扱っているの？
> 
> https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#modifying-control-values

hardware_interface側では、homing offsetを考慮していないように見えます。具体的には、サーボ内部でhoming offsetによって補正された値をそのまま読み取る形になっており、値を書き込む際もhoming offsetの補正処理はサーボ側で行われているように見えます。実機で試してみます

2024-11-26 06:03 UTC, ChiroruNeko commented
> 後 ベースブランチは XMではなかったっけ？

ベースブランチがXMである旨承知いたしました。マージ先を変更します

2024-11-26 06:21 UTC, Tacha-S commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
https://github.com/sbgisen/dynamixel_control_hw/pull/5#pullrequestreview-2460264861 にもつながると思うけど、
ここと下にある[-pi, pi)への正規化の部分はどういう問題があってどう解決したんですか？

2024-11-26 08:12 UTC, ChiroruNeko commented
> > Offsetについてだけど、確か dynamixel側で homing offsetを設定すると0〜2piから-pi〜piに変更できると思う。hardware interface 側はどう扱っているの？
> > https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#modifying-control-values
> 
> hardware_interface側では、homing offsetを考慮していないように見えます。具体的には、サーボ内部でhoming offsetによって補正された値をそのまま読み取る形になっており、値を書き込む際もhoming offsetの補正処理はサーボ側で行われているように見えます。実機で試してみます

実機で試したところ、homing offsetはサーボ側で補正されているようでした。ただ、-90deg~90degの範囲でしか設定できないため使えなさそうです（https://forum.robotis.com/t/setting-homing-offset-in-dynamixel-wizard-2-0/1674 ）。

2024-11-26 09:29 UTC, ChiroruNeko commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
- 問題
`XH540`は0～4096の範囲で指令値を受け取ります。`libdynamixel`では、`XH540`のポジションの最小値が0、最大値が360degとして扱われ、入力値を0～4096に変換してサーボに送信します。そのため、`libdynamixel`を用いる場合、位置指令値は正の値である必要があり、`libdynamixel`に手を加えない場合ノード側で位置指令の範囲を変換する必要があります。

- 解決方法（実装）
サーボへの指令値（`servo_angle`）は以下の式で計算しています。
`servo_angle = (joint_angle - offset - rising_offset) * gear_ratio`
ここで、`offset`と`rising_offset`は、`joint_angle`が0のときに`servo_angle`が`π`になるよう調整します。これにより`joint_angle`が`[-π / gear_ratio, π / gear_ratio)`の範囲内であれば、サーボへの指令値（servo_angle）は`[0, 2π)`となるはずです。

現在、範囲外のstateやcommandも無理やり有効な範囲内に変換していましたが、エラーを出力する方が適切と感じたのでこの部分を修正しようかと思います。

2024-11-26 09:57 UTC, Tacha-S commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
もとの実装が有効範囲考えてなかったってことですね。
このままでもいいような気がします。

2024-11-26 09:58 UTC, Tacha-S requested changes

2024-11-26 09:58 UTC, Tacha-S commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] += _dynamixel_rising_offsets[_servos[i]->id()];
`offset` がないと `rising` が反映されないのはちょっと不便なので独立させてください。

2024-11-26 10:17 UTC, ChiroruNeko commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
writeでは以下の関数が使われていますが、joint_limitsが定義されていない場合もあるかと思い念の為…
https://github.com/sbgisen/dynamixel_control_hw/blob/02a718453b178e3969f245c3f8413ed32aaa0261/include/dynamixel_control_hw/hardware_interface.hpp#L379-L380

このままでも良い旨承知いたしました

2024-11-26 10:17 UTC, ChiroruNeko commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] += _dynamixel_rising_offsets[_servos[i]->id()];
承知しました

2024-11-27 01:34 UTC, Tacha-S commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
ちなみになんですけどマルチターンはdynamixelって対応していないんですか？
そうなるとギア比高すぎてheadの可動域(特にpan)が対応できないのでは？

2024-11-27 03:00 UTC, ChiroruNeko commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
マルチターン機能は存在するようです。また、現在、FRAの`E20-H08-50`（ストールトルク3.2N.m）を減速比2.608で使用していますが、XH540のストールトルクが9.9N.mと余裕があるため、最悪等倍で使えば可動域も問題ないかと思います。

2024-11-27 05:05 UTC, jsupratman13 commented
> > > Offsetについてだけど、確か dynamixel側で homing offsetを設定すると0〜2piから-pi〜piに変更できると思う。hardware interface 側はどう扱っているの？
> > > https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#modifying-control-values
> > 
> > 
> > hardware_interface側では、homing offsetを考慮していないように見えます。具体的には、サーボ内部でhoming offsetによって補正された値をそのまま読み取る形になっており、値を書き込む際もhoming offsetの補正処理はサーボ側で行われているように見えます。実機で試してみます
> 
> 実機で試したところ、homing offsetはサーボ側で補正されているようでした。ただ、-90deg~90degの範囲でしか設定できないため -pi ~ piにできなさそうです（https://forum.robotis.com/t/setting-homing-offset-in-dynamixel-wizard-2-0/1674 ）。

https://forum.robotis.com/t/setting-homing-offset-in-dynamixel-wizard-2-0/1674 のリンクは何のリンク？ -90~90について何も書いていない？

2024-11-27 06:38 UTC, Tacha-S commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
なるほど。
等倍で使った場合も`rising=0` かつ `offset=0` で正面向けていないと変な位置を基準に左回転、右回転が切り替わりそうですね
個人的にはマルチターン対応しておいたほうが良さそうに思いますが、noeticはまあそれでもいいのかもしれないです。

2024-11-28 02:10 UTC, ChiroruNeko commented
> > > > Offsetについてだけど、確か dynamixel側で homing offsetを設定すると0〜2piから-pi〜piに変更できると思う。hardware interface 側はどう扱っているの？
> > > > https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#modifying-control-values
> > > 
> > > 
> > > hardware_interface側では、homing offsetを考慮していないように見えます。具体的には、サーボ内部でhoming offsetによって補正された値をそのまま読み取る形になっており、値を書き込む際もhoming offsetの補正処理はサーボ側で行われているように見えます。実機で試してみます
> > 
> > 
> > 実機で試したところ、homing offsetはサーボ側で補正されているようでした。ただ、-90deg~90degの範囲でしか設定できないため -pi ~ piにできなさそうです（https://forum.robotis.com/t/setting-homing-offset-in-dynamixel-wizard-2-0/1674 ）。
> 
> https://forum.robotis.com/t/setting-homing-offset-in-dynamixel-wizard-2-0/1674 のリンクは何のリンク？ -90~90について何も書いていない？

すみません、リンクを間違っていました…正しくはこちらです
https://forum.robotis.com/t/dynamixel-set-zero-position/5317/4

2024-11-28 02:21 UTC, ChiroruNeko commented on include/dynamixel_control_hw/hardware_interface.hpp
> +                    _joint_angles[i] = -_joint_angles[i];
承知しました。
マルチターンもハードの区切りがつき次第試してみようと思います。もし何か問題が起きたらいったんは、`rising=0` かつ `offset=0` 、dynamixelの角度180度で顔が正面を向くように取り付けようと思います。

2024-12-02 10:25 UTC, jsupratman13 reviewed
1. libdynamixelのレポジトリ・ブランチ何使っているか分からないので，READMEにメモするか，submoduleにしてもいい，CMakeLists.txtと共に楽にインストールしてもいい気がする．
2. ~~-π to π→0 to 2π の部分は必要だっけ？サンプルの用にoffsetを設定すると-π to πにしても大丈夫だけど？~~

2024-12-02 10:25 UTC, jsupratman13 commented on launch/sample.launch
> +          args="/dynamixel_controllers/traj_controller
pos_controller　だよ

2024-12-02 10:25 UTC, jsupratman13 commented on launch/sample.launch
sample.launch修正しなくてもいい

2024-12-02 10:25 UTC, jsupratman13 commented on urdf/sample.urdf
sample.urdfも修正しなくてもいい

2024-12-05 01:22 UTC, ChiroruNeko commented
> 1. libdynamixelのレポジトリ・ブランチ何使っているか分からないので，READMEにメモするか，submoduleにしてもいい，CMakeLists.txtと共に楽にインストールしてもいい気がする．

反応が遅くなり申し訳ございません．READMEに追加しつつCMakeLists.txtでインストールできるように修正したいと思います．来週までに対応いたします．

2024-12-05 01:30 UTC, ChiroruNeko commented
@jsupratman13 
sample.launch, urdf, yamlに加えた変更をrevertしました

2024-12-10 10:43 UTC, Tacha-S commented
libdynamixelは以下のブランチで動作可能です。

https://github.com/sbgisen/libdynamixel/pull/9

~ただし、仕様なのかわかりませんが、
1回転以上した状態で再起動すると、現在位置が`[0, 2pi)`の範囲に変わります。(起動中は変化しない)~

rebootをtorque enableに失敗したときのみ(失敗したらstatus validがfalseになるのかはわからないが)にしたので、
上記の現象は起きなくなりました。
エラー発生時に正しく再起動できるかは不明　

2025-01-15 10:59 UTC, Tacha-S commented
gear_ratio周りおそらく間違ってる

2025-01-15 14:52 UTC, ChiroruNeko commented
申し訳ございません、自分が変更を加えた箇所です…明日朝一で対応いたします。

2025-01-15 23:39 UTC, Tacha-S commented
いや、こっちで見とくので大丈夫ですよ

2025-01-16 01:00 UTC, ChiroruNeko commented
> いや、こっちで見とくので大丈夫ですよ

ご迷惑おかけし申し訳ございません...
こちらのコメントをいただく前に実施した作業と確認した内容を参考までに共有いたします．すでにご存知でしたらご放念ください．
- 2025/01/16の時点ではtilt軸の減速比が1/1.2でしたが，プーリーを交換し等倍に変更しました．交換後，
tilt軸の減速比を等倍にした状態で動作を確認しました．
- writeとreadにおける角度の変換は，単位の変換以外fraのhw_interfaceと同様のつもりで実装しておりましたが，変換周りでバグは見つけられませんでした．．．以下の変換のためギア比を変えるとrisingやoffsetも変える必要があります．
  - read: <出力軸の現在角度> = <現在サーボ角度> / gear_ratio * <回転方向を表す符号> + <オフセット>
  - write: <サーボへの角度指令> = (<出力軸の目標角度> - <オフセット>) * gear_ratio * <回転方向を表す符号>
- tilt軸においてgear_ratio = 2.0, 目標値を1.57radとしたところサーボが3.14rad動作することは確認しました．
- soar.launch実行時にpan, tiltに与えられる目標値は最後に与えられた目標値が再送されるようです．そのため，reverseの値を切り替える際は注意が必要です．具体的には，最後に目標値0.1を与え，reverseを変更しそのままsoar.launchすると0.1から-0.1まで遠回りの経路を通り回転します．初期値を0で固定したほうが良いかもしれません．

お時間いただき申し訳ございませんが引き続きよろしくお願いいたします．

2025-01-16 01:10 UTC, Tacha-S commented
等倍にしたら正しく動いたのか動いてないのかはどちらですか？

2025-01-16 01:10 UTC, ChiroruNeko commented
正しく動いているように見えます

2025-01-16 01:12 UTC, Tacha-S commented
ではコードを見た感じはあっていそうだし、このままでいいかな

2025-01-16 01:16 UTC, ChiroruNeko commented
ご確認いただきありがとうございます！承知いたしました．引き続きよろしくお願いいたします．

2025-01-16 07:53 UTC, jsupratman13 reviewed
soar向けPRなのでこのままでいいけど、どうする？汎用性にしますか？

2025-01-16 08:02 UTC, Tacha-S commented
これをROS2化するわけでもないので、自分は動けばもうメンテする気はあまりないです。
このままもしくはsoar用にブランチを切る程度かなと思ってました。

2025-01-16 08:05 UTC, jsupratman13 commented
ok

2025-01-16 08:05 UTC, jsupratman13 approved these changes

2025-01-16 08:06 UTC, merged